---
# based on instructions found in the docker documentation here:
# https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: "Install necessary key signature checking keys and tools"
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - apt-transport-https
  - ca-certificates

- name: "Does the docker apt file exist?"
  command: test -f {{docker_apt_file}}
  register: docker_apt_exists
  ignore_errors: True

- name: "Add docker's GPG key to apt"
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: "Add Docker repo"
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-xenial main" dest={{docker_apt_file}} owner=root group=root mode=644
  when: docker_apt_exists.rc == 1

- name: "Update apt cache"
  apt: update_cache=yes
  when: docker_apt_exists.rc == 1

- name: "Install supporting packages"
  apt: pkg={{ item }} state=present
  with_items:
  - linux-image-extra-virtual
  - "linux-image-extra-{{ ansible_kernel }}"

- name: "Install Docker Engine"
  apt: pkg=docker-engine state=installed

- name: "Start Docker service"
  service: name=docker state=restarted

- name: "Create docker group"
  group: name=docker state=present

- name: "add users to docker group"
  user: name={{ user_name }} groups="docker" append=yes
