---

- include_vars: vault.yml

- name: "install tools"
  apt: name={{ item }} state=present update_cache=true
  with_items:
  - irssi
  - nmap
  - vim
  - links 
  - terminator
  - screen
  - tmux
  - jq
  - dhcpdump
#  - vivaldi


- name: "install tools that require gui"
  apt: name={{ item }} state=present update_cache=true
  with_items:
  - inkscape
  tags:
  - gui

- name: "Setup User account"
  include: user_setup.yml

- name: "install docker from the docker git repo"
  include: docker.yml
  tags:
  - bare_metal

- name: "install chrome"
  include: chrome.yml
  tags: 
  - gui
