
- ec2_vpc:
    state: present
    resource_tags: { "name":"prod" }
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    cidr_block: 172.37.0.0/16
    resource_tags: { "Environment":"Development" }
    region: us-west-2
    dns_support: true
    dns_hostnames: true
    wait: yes
    internet_gateway: yes 
    route_tables:
      - subnets:
          - 172.37.1.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    subnets:
      - cidr: 172.37.1.0/24
        resource_tags: { "Environment":"Dev", "Tier" : "Web" }
  register: vpc

- name: example ec2 group
  ec2_group:
    name: IRC
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    description: all necessary ports for IRC 
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc.vpc.region }}"
    region: us-west-2
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 6660
        to_port: 6669
        cidr_ip: 0.0.0.0/0

- local_action: 
    module: ec2
    instance_type: t2.nano
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    image: ami-9abea4fb 
    key_name: alex.public
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    assign_public_ip: yes
    wait: yes
    count: 1
    group: IRC
    region: us-west-2
    instance_tags: 
      class: irc_client
  register: ec2

- name: Add all instance public IPs to host group
  add_host: name={{ item.public_ip }} group=irc_client  ansible_ssh_user=ubuntu
  with_items: ec2.instances

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=6000 state=started
  with_items: ec2.instances

